version: '3'
services:

  redis:
    container_name: auth_cache
    image: "bitnami/redis:latest"
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    environment: 
      - REDIS_PASSWORD=password
  
  redis-commander:
    container_name: auth_cache_dash
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379:0:password
    - REDIS_PASSWORD=password
    ports:
    - "8081:8081"

  mongo:
    container_name: auth_bdd
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - bdd:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    container_name: auth_bdd_dash
    image: mongo-express
    restart: always
    ports:
      - "8080:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

volumes:
    bdd:
    redis_data:
